
/**
 * Calculate the total TP generated by a single hit at a given delay with a given amount of StoreTP
 * @param {Number} modifiedDelay total delay after dual-wield and martial arts but excluding haste
 * @param {Number} storeTp Total quantity of StoreTp across gearset
 * @returns {Number}
 */
export function tpPerHit(modifiedDelay, storeTp) {
    //this function will be full of magic numbers. nothing to be done about it.
    let total = 0
    if (modifiedDelay < 180) {
        total = 61 + (((modifiedDelay - 180) * 63) / 360)
    } else if (modifiedDelay < 541) {
        total = 61 + (((modifiedDelay - 180) * 88) / 360)
    } else if (modifiedDelay < 631) {
        total = 149 + (((modifiedDelay - 540) * 20) / 360)
    } else if (modifiedDelay < 721) {
        total = 154 + (((modifiedDelay - 630) * 28) / 360)
    } else if (modifiedDelay < 901) {
        total = 161 + (((modifiedDelay - 720) * 24) / 360)
    } else {
        total = 173 + (((modifiedDelay - 900) * 28) / 360)
    }
    return Math.floor(total) + Math.floor(total * (storeTp/100))
}